print("Hello World")
print("Hello \n World")
print("Hello \t World")
print("Hello \\ World")
print("Hello \' World")
print("Hello \" World")     

msg= input("Enter your message: ")
msg= msg.replace(":)", "😊")
msg= msg.replace(":(", "😞")
msg= msg.replace(":P", "😛")
msg= msg.replace(":/", "😕")
msg= msg.replace(":D", "😄")
msg= msg.replace("<3", "❤️")
msg= msg.replace(";)", "😉")
print("Your updated message is: ", msg) 