str= "Payal"
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.title())
print(str.count('a'))
print(str.find('y'))
print(str.replace('Payal', 'Kumari'))
print(str.isalpha())
print(str.isdigit())
print(str.startswith('P'))
print(str.endswith('l'))
print(str.split('a'))
print(str.strip())
print(str.center(20, '*'))
print(str.ljust(20, '-'))
print(str.rjust(20, '+'))
print(str.swapcase())
print(str.encode())
print(str.partition('y'))
print(str.zfill(10))
print(str.count('P'))
